apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: nfs-pv-static-provisioner
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
